### ISSUE TITLE
dimension out of range (expected to be in range of [-1, 0], but got 2)

### ISSUE THREAD

**Issue by sgc123** [B-Manifold/pytorch_fnet_UwUnet#3]
《use Training Indian Pines with Provided Data》 part
when I use command ./scripts/test_indian_pines.sh indian_pines 0
I met the problem is as the title.
could anyone solve the problem?

class_dataset TiffDataset --transform_signal fnet.transforms.normalize --transform_target fnet.transforms.normalize --patch_size 64 64 --batch_size 32 --buffer_size 6 --buffer_switch_frequency 16000 --path_run_dir saved_models/indian_pines1 --gpu_ids 0
Model instianted from: fnet_nn_UwU
fnet_nn_UwU | {} | iter: 0
<fnet.data.tiffdataset.TiffDataset object at 0x7f3134305828>
buffering images: 100%|#############################################################################################################################################################| 6/6 [00:00<00:00, 10.17it/s]
Traceback (most recent call last):
  File "train_model.py", line 160, in <module>
    main()
  File "train_model.py", line 126, in main
    for i, (signal, target) in enumerate(dataloader_train, model.count_iter):
  File "/root/anaconda3/envs/fnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/root/anaconda3/envs/fnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/root/fnet/pytorch_fnet_UwUnet-1.0.0/fnet/data/bufferedpatchdataset.py", line 78, in __getitem__
    return self.get_random_patch()
  File "/root/fnet/pytorch_fnet_UwUnet-1.0.0/fnet/data/bufferedpatchdataset.py", line 137, in get_random_patch
    patch = [(datum[0])[tuple(index)]]
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 2)

**Comment by EarendelSK** [comment]
Hi, did you fix this? I am facing the same problem as you now.
